In [1]:
setwd("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/bulk/hahn_2023/cortex")

source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/enrichment_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/gene_mapping_fxns.R")
source("/mnt/lareaulab/reliscu/projects/NSF_GRFP/analyses/code/top_corr_module_fxns.R")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: future


Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths



Attaching package: ‘data.table’


The following objects are masked from ‘package:reshape2’:

    dcast, melt


The following objects are masked from ‘package:dplyr’:

    between, first, last

Here I perform enrichment analysis to find modules enriched for cell type markers. 

These modules will later be used to correlate with exon PSI to define cell type-specific exons.

In [2]:
n_workers <- 20
mod_def <- "TopModPosBC"

max_set_size <- 200
min_set_size <- 3

## Prep marker genes

### Claude marker genes

In [ ]:
# set_source <- "Claude_marker_genes"

# marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/AI/Claude_cortical_markers_mouse.RDS")

### MO marker genes

In [ ]:
load("/mnt/lareaulab/reliscu/data/gene_sets/Oldham/MO_sets.RData")

mask <- !MO_legend$Category %in% "Disease"
marker_genes_list <- MO_sets[mask]
names(marker_genes_list) <- MO_legend$SetName[mask]

set_sizes <- lengths(marker_genes_list)
mask <- (set_sizes < max_set_size) & (set_sizes > min_set_size)
marker_genes_list <- marker_genes_list[mask]

print(length(marker_genes_list))

set_source <- paste0("MO_", length(marker_genes_list), "sets")

[1] 1271

### Gugene DE genes

In [ ]:
# marker_source <- "kang_2026_intersection"
# marker_genes_list <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/kang_2026_preprint/kang_2026_preprint_DE_genes.RData")

# # marker_source <- "kang_2026_union"
# # marker_genes_list1 <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/kang_2026_preprint/kang_2026_preprint_Jorstad_2023_DE_genes.RData")
# # marker_genes_list2 <- readRDS("/mnt/lareaulab/reliscu/projects/NSF_GRFP/data/marker_genes/kang_2026_preprint/kang_2026_preprint_Gabitto_2024_DE_genes.RData")
# # marker_genes_list <- lapply(seq_along(marker_genes_list1), function(i) {
# #     union(marker_genes_list1[[i]], marker_genes_list2[[i]])
# # })
# # names(marker_genes_list) <- names(marker_genes_list1)

## Get enrichments

In [ ]:
network_dir <- "hahn_2023_cortex_STAR_counts_TMMF_All_130_outliers_removed_mergeParam0.95_minSignum0.84_subsetCutoff2.424_Modules"

enrichments_df <- get_module_enrichments_par(network_dir, marker_genes_list, mod_def, n_workers)

# enrichments_df <- get_module_enrichments(network_dir, marker_genes_list, mod_def)

write.csv(enrichments_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments.csv"), row.names=FALSE, quote=FALSE)

# Get most enriched cell type for each module
# If cell type is most enriched in multiple modules, choose module with smallest p-value

top_mods_df <- enrichments_df %>%
    group_by(Cell_type) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    group_by(Network, Module) %>%
    arrange(Network) %>%
    slice_min(Qval, with_ties=FALSE) %>%
    arrange(Qval)
    
top_mods_df[,c("Cell_type", "Pval", "Qval", "Module", "Network")]

# get_mod_vs_DE_genes(top_mods_df, marker_genes_list, mod_def)

write.csv(top_mods_df, file=paste0("data/enrichments/", network_dir, "_", set_source, "_enrichments_top_Qval_mods.csv"), row.names=FALSE, quote=FALSE)

Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt



Attaching package: ‘reshape2’


The following objects are masked from ‘package:data.table’:

    dcast, melt

   Cell_type                       Pval         Qval         Module
1  LIQUN_FIBROBLAST_DCNcor         4.471024e-16 9.944676e-11 black
2  GOKCE_D1MSN                     6.450695e-14 2.869592e-09 brown
3  GOKCE_EPENDYMAL_CILIA_STR       1.362724e-10 9.474198e-07 brown
4  GOKCE_D1_CXCL14_MSN             1.696924e-10 1.110113e-06 yellow
5  MANCARCI_CHOLINERGIC_BF         2.292053e-08 6.536025e-05 brown
6  MANCARCI_DG_HIP                 4.789566e-08 1.238743e-04 brown
7  GOKCE_EPENDYMAL_SEC_STR         7.669113e-08 1.814684e-04 purple
8  GOKCE_VASCULAR_STR              1.249519e-07 2.698294e-04 blue
9  MANCARCI_CHOLINERGIC_SC         1.219024e-07 2.698294e-04 blue
10 MANCARCI_SPINY_STR              1.324982e-07 2.780274e-04 yellow
11 MANCARCI_GabaSSTReln_HIP        2.653410e-06 3.451373e-03 yellow
12 MANCARCI_EPENDYMAL              2.989253e-06 3.676557e-03 grey60
13 LOH_EXCITATORY_SYNAPSE_PROTEOME 3.037742e-06 3.692184e-03 blue
14 GOKCE_OPC_STR                   1.021067e-05 9.831635e-03 green
15 MANCARCI_CHOLINERIGIC_THAL      1.123507e-04 6.922328e-02 cyan
16 LOH_INHIBITORY_SYNAPSE_PROTEOME 6.019260e-04 2.923218e-01 blue
17 ABA_ASTROCYTES                  1.000000e+00 1.000000e+00 blue
   Network
1  Bicor-None_signum0.956_minSize4_merge_ME_0.95_19459
2  Bicor-None_signum0.95_minSize3_merge_ME_0.95_19459
3  Bicor-None_signum0.95_minSize8_merge_ME_0.95_19459
4  Bicor-None_signum0.956_minSize3_merge_ME_0.95_19459
5  Bicor-None_signum0.953_minSize3_merge_ME_0.95_19459
6  Bicor-None_signum0.959_minSize4_merge_ME_0.95_19459
7  Bicor-None_signum0.956_minSize3_merge_ME_0.95_19459
8  Bicor-None_signum0.95_minSize4_merge_ME_0.95_19459
9  Bicor-None_signum0.965_minSize10_merge_ME_0.95_19459
10 Bicor-None_signum0.95_minSize3_merge_ME_0.95_19459
11 Bicor-None_signum0.95_minSize4_merge_ME_0.95_19459
12 Bicor-None_signum0.95_minSize3_merge_ME_0.95_19459
13 Bicor-None_signum0.959_minSize6_merge_ME_0.95_19459
14 Bicor-None_signum0.956_minSize6_merge_ME_0.95_19459
15 Bicor-None_signum0.953_minSize3_merge_ME_0.95_19459
16 Bicor-None_signum0.959_minSize8_merge_ME_0.95_19459
17 Bicor-None_signum0.95_minSize10_merge_ME_0.95_19459

## Compare enrichments

In [48]:
x <- list.files("data/enrichments")[grep(set_source, list.files("data/enrichments"))]

enrichments_list <- lapply(x, function(y) {
    split <- unlist(strsplit(y, "STAR_"))
    prefix <- unlist(strsplit(split[2], "_mergeParam"))[1]
    middle <- gsub("p_", "p", unlist(strsplit(split[2], "yao_2021_"))[2])
    suffix <- gsub("_enrichments.csv", "", unlist(strsplit(split[3], "DE_genes_"))[2])
    dataname <- paste(prefix, paste(middle, suffix, sep="_"), sep="_")

    enrich_df <- fread(file.path("data/enrichments", y), data.table=FALSE)
    enrich_df <- enrich_df[,c("Cell_type", "Qval")]
    colnames(enrich_df)[2] <- dataname
    enrich_df
})

enrichment_table <- Reduce(f=function(x, y) {
    merge(x, y, by="Cell_type", all=TRUE)
}, enrichments_list)

In [49]:
enrichment_table

   Cell_type         counts_All_130_outliers_removed_NA_NA
1  All GABAergic     5.435243e-02
2  All Glutamatergic 6.373157e-02
3  All Neuronal      1.183839e-04
4  Astro             6.391156e-06
5  CGE Class         6.789348e-01
6  Chandelier        9.085627e-01
7  Endo              1.522491e-06
8  L2/3 IT           2.330007e-01
9  L4 IT             5.016422e-04
10 L5 ET             7.828274e-02
11 L5 IT             1.531839e-01
12 L5/6 NP           2.009563e-01
13 L6 CT             4.549936e-04
14 L6 IT             2.798800e-01
15 L6 IT Car3        1.000000e+00
16 L6b               6.706732e-04
17 Lamp5             6.321172e-03
18 Lamp5 Lhx6        7.153864e-01
19 MGE Class         2.908820e-02
20 Micro/PVM         2.717410e-15
21 Oligo             3.801377e-26
22 OPC               1.637234e-04
23 Pax6              8.483360e-01
24 Peri              2.330007e-01
25 Pvalb             4.361837e-04
26 Sncg              1.150040e-01
27 Sst               5.916665e-02
28 Sst Chodl         7.485620e-01
29 Vip               2.331357e-02
30 VLMC              1.263942e-05
   counts_All_130_Qnorm_NA_NA TPM_All_94_outliers_removed_NA_NA
1  3.725008e-02               1.000000e+00
2            NA               2.285138e-03
3  2.303499e-03               1.679750e-03
4  8.773127e-09               1.062546e-03
5  8.290594e-01                         NA
6  9.435906e-01                         NA
7  5.596723e-07               1.672258e-07
8  1.000000e+00                         NA
9  2.653078e-04               5.508852e-02
10 3.496998e-01                         NA
11 8.987975e-01               1.474823e-01
12           NA                         NA
13 2.762882e-02               7.698444e-03
14 8.898820e-01               3.576070e-02
15 8.290594e-01               9.912813e-01
16 1.814555e-01               1.263601e-02
17 1.335750e-01                         NA
18 7.196165e-01               6.371819e-01
19 6.718966e-01               1.379575e-02
20 1.567261e-21               3.799287e-04
21 1.226797e-23               2.892204e-25
22 7.182793e-04               3.827572e-04
23           NA                         NA
24 9.435906e-01               9.250963e-01
25 9.979876e-02               5.150326e-03
26 2.003281e-01               9.261071e-03
27 2.924294e-01               7.681586e-02
28 9.480167e-03                         NA
29 6.885636e-02               4.028874e-02
30 2.262317e-04               4.243214e-05

In [52]:
data.frame(colMeans(enrichment_table[,-1], na.rm=TRUE))

                                      colMeans.enrichment_table....1...na.rm...TRUE.
counts_All_130_outliers_removed_NA_NA 0.2143810
counts_All_130_Qnorm_NA_NA            0.3381299
TPM_All_94_outliers_removed_NA_NA     0.1801532

# Test

In [ ]:
df <- fread("")