In [2]:
import os
import re
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sys.path.append("/mnt/lareaulab/reliscu/code")

from parse_gtf import *
from junction2psi import *

pd.set_option('display.max_columns', None)

In [3]:
corr_df = pd.read_csv("data/corrs/hahn_2023_cortex_STAR_counts_TMMF_All_130_outliers_removed_Claude_marker_genes_PC1_ctype_abundance_exon_counts_corr.csv", index_col=0)

In [4]:
corr_df.head()

,Gene,All Neuronal,All Glutamatergic,All GABAergic,CGE Class,MGE Class,L4 IT,L6 CT,L6 IT Car3,Sncg,Pvalb,Sst,Sst Chodl,Astro,Oligo,Endo,VLMC,Peri,L4 L5 IT,Vip Sncg
ENSMUSG00000025902_ProteinCoding_1,Sox17,0.704820,0.712606,0.685048,0.592332,0.618572,0.602368,0.550662,0.571557,0.592124,0.575845,0.487906,0.180897,0.726523,0.544935,0.704356,0.150673,0.115180,0.623887,0.608719
ENSMUSG00000025902_ProteinCoding_2,Sox17,0.706066,0.713623,0.682193,0.585042,0.617292,0.616523,0.549923,0.565232,0.586625,0.576586,0.485358,0.171957,0.727870,0.535255,0.706896,0.148453,0.112848,0.625975,0.624372
ENSMUSG00000025902_ProteinCoding_3,Sox17,0.356319,0.361247,0.318949,0.216859,0.283328,0.143687,0.271799,0.282952,0.314251,0.280414,0.232569,0.088818,0.341162,0.289881,0.304612,0.077093,0.043558,0.336717,0.149327
ENSMUSG00000025902_ProteinCoding_4,Sox17,0.465436,0.470932,0.416033,0.279767,0.347572,0.264590,0.364281,0.305548,0.367779,0.434841,0.248640,0.084684,0.432308,0.374428,0.374598,0.033845,0.005814,0.454376,0.251553
ENSMUSG00000033845_ProteinCoding_1,Mrpl15,0.896632,0.866385,0.941678,0.861636,0.937214,0.551563,0.618362,0.920686,0.910495,0.557476,0.859579,0.541323,0.950891,0.585404,0.832032,0.457440,0.467041,0.711256,0.508402

In [ ]:
# L6 CT is oligo

# Sst Chodl is not well defined (excitatory markers)

# Endo is suss (includes neuronal markers, might be metabolic)

# L6 IT Car3 has some evidence of  brain abnormalities (Apoe, Gas5)

# Sncg is not specific... could be broadly neuronal
# MGE Class is the same ^
# CGE Class is the same ^

# All Glutamatergic looks broadly neuronal
# All GABAergic looks like a housekeeping gene signature

In [32]:
corr_df.sort_values("All GABAergic", ascending=False).head(50)

,Gene,All Neuronal,All Glutamatergic,All GABAergic,CGE Class,MGE Class,L4 IT,L6 CT,L6 IT Car3,Sncg,Pvalb,Sst,Sst Chodl,Astro,Oligo,Endo,VLMC,Peri,L4 L5 IT,Vip Sncg
ENSMUSG00000027523_ProteinCoding_4,Gnas,0.934976,0.908254,0.980993,0.894890,0.962348,0.530051,0.671006,0.905990,0.942193,0.615895,0.849840,0.563172,0.971806,0.662378,0.838399,0.429144,0.445551,0.777189,0.500806
ENSMUSG00000029580_ProteinCoding_1,Actb,0.944052,0.920333,0.980818,0.885345,0.954745,0.581961,0.694524,0.899162,0.926300,0.629081,0.835238,0.522237,0.975977,0.664725,0.855946,0.399881,0.415151,0.784803,0.558849
ENSMUSG00000029580_other_1,Actb,0.933763,0.908936,0.979883,0.894818,0.959059,0.576783,0.678759,0.907840,0.928188,0.612124,0.846485,0.539759,0.972776,0.646964,0.852966,0.414843,0.432612,0.770128,0.549981
ENSMUSG00000027523_ProteinCoding_3,Gnas,0.939425,0.915371,0.979794,0.887222,0.953222,0.536842,0.682901,0.890239,0.930945,0.629943,0.830076,0.546240,0.968656,0.675338,0.834857,0.401735,0.421915,0.788914,0.511676
ENSMUSG00000030695_ProteinCoding_2,Aldoa,0.923449,0.894792,0.974735,0.901317,0.967933,0.513680,0.670222,0.932045,0.954129,0.574666,0.879811,0.575948,0.969424,0.645044,0.838381,0.477543,0.485053,0.748174,0.489304
ENSMUSG00000038965_ProteinCoding_1,Ube2l3,0.907149,0.874616,0.973398,0.907977,0.972054,0.485130,0.634555,0.936228,0.955780,0.560808,0.889551,0.606696,0.959279,0.612461,0.814290,0.497206,0.509908,0.732096,0.444459
ENSMUSG00000022564_ProteinCoding_3,Grina,0.930983,0.906653,0.973383,0.877841,0.951490,0.598576,0.650730,0.905332,0.914202,0.623397,0.839918,0.521311,0.974969,0.622040,0.869590,0.418438,0.429026,0.771265,0.559969
ENSMUSG00000022564_ProteinCoding_2,Grina,0.933160,0.909287,0.972804,0.875653,0.949364,0.598576,0.654860,0.902484,0.912486,0.629260,0.836332,0.517548,0.975101,0.628666,0.869813,0.411000,0.423686,0.775338,0.560352
ENSMUSG00000028843_ProteinCoding_1,Sh3bgrl3,0.951053,0.927298,0.972708,0.871983,0.943327,0.574271,0.705880,0.883428,0.918001,0.644606,0.819885,0.496864,0.976141,0.688551,0.850883,0.371539,0.387978,0.799793,0.572965
ENSMUSG00000022564_ProteinCoding_1,Grina,0.935693,0.912790,0.972637,0.873465,0.947045,0.597902,0.664098,0.897629,0.910407,0.636353,0.831184,0.513392,0.974679,0.639319,0.866431,0.401599,0.416089,0.780292,0.561756
ENSMUSG00000021282_ProteinCoding_1,Eif5,0.929138,0.903687,0.972055,0.884609,0.952827,0.562153,0.659498,0.901320,0.925085,0.624563,0.844097,0.527209,0.972067,0.643052,0.857376,0.428933,0.434616,0.777838,0.529233
ENSMUSG00000014195_ProteinCoding_3,Dnajc7,0.927229,0.898081,0.971867,0.881727,0.961565,0.551875,0.662539,0.906005,0.932826,0.611959,0.851219,0.538276,0.970467,0.639969,0.837431,0.433465,0.441390,0.767105,0.520199
ENSMUSG00000061518_ProteinCoding_2,Cox5b,0.919328,0.885161,0.971599,0.891890,0.961239,0.526013,0.654346,0.933621,0.948712,0.582062,0.880135,0.566586,0.970144,0.631302,0.830224,0.486045,0.483964,0.746813,0.499141
ENSMUSG00000024099_ProteinCoding_1,Ndufv2,0.943960,0.915156,0.971393,0.864922,0.946020,0.557885,0.689985,0.892281,0.927142,0.654197,0.830775,0.502000,0.978125,0.672051,0.839783,0.419889,0.416479,0.800213,0.530147
ENSMUSG00000038717_ProteinCoding_1,Atp5mg,0.948419,0.923572,0.971227,0.865531,0.939308,0.598017,0.686991,0.892224,0.911106,0.655350,0.821429,0.481200,0.981084,0.669816,0.857493,0.385886,0.386739,0.804854,0.579143
ENSMUSG00000014195_ProteinCoding_4,Dnajc7,0.941823,0.915735,0.971188,0.863662,0.946102,0.570237,0.682994,0.882582,0.919704,0.652774,0.819134,0.496421,0.971678,0.666631,0.849163,0.391273,0.399187,0.797178,0.538664
ENSMUSG00000024099_ProteinCoding_2,Ndufv2,0.943486,0.914145,0.971179,0.865342,0.946223,0.556184,0.689419,0.893342,0.927964,0.652940,0.832192,0.504804,0.977935,0.672018,0.839469,0.421750,0.418920,0.799155,0.528302
ENSMUSG00000071644_other_1,Eef1g,0.915710,0.888725,0.970960,0.894356,0.959564,0.556314,0.662701,0.913422,0.935511,0.583945,0.858661,0.556323,0.963821,0.625608,0.827922,0.454128,0.462980,0.745158,0.527041
ENSMUSG00000029152_ProteinCoding_2,Ociad1,0.908236,0.876082,0.970793,0.897846,0.968961,0.526206,0.626718,0.939339,0.946604,0.555810,0.888780,0.589176,0.963463,0.602694,0.838393,0.491934,0.504015,0.730896,0.495495
ENSMUSG00000090841_NMD_1,Myl6,0.938101,0.909669,0.970498,0.872593,0.953020,0.562340,0.675524,0.912904,0.930313,0.614573,0.854595,0.522178,0.977449,0.651251,0.847064,0.430105,0.438246,0.772201,0.540788
ENSMUSG00000027108_ProteinCoding_1,Ola1,0.938541,0.905611,0.970496,0.875002,0.946410,0.498421,0.686861,0.889158,0.936931,0.629106,0.836079,0.543641,0.962880,0.685582,0.815189,0.419963,0.431407,0.792625,0.481475
ENSMUSG00000061518_ProteinCoding_1,Cox5b,0.917545,0.883049,0.970348,0.890160,0.960409,0.523158,0.653354,0.933187,0.948935,0.580369,0.880291,0.566829,0.968807,0.629882,0.828576,0.489615,0.485692,0.744588,0.495120
ENSMUSG00000029152_ProteinCoding_1,Ociad1,0.912609,0.882532,0.970333,0.892610,0.967685,0.532552,0.638134,0.934977,0.943503,0.564568,0.882456,0.577112,0.965141,0.610311,0.844033,0.482043,0.493380,0.737506,0.501160
ENSMUSG00000022841_ProteinCoding_1,Ap2m1,0.954885,0.931478,0.970265,0.858446,0.949948,0.542004,0.710251,0.897192,0.928675,0.646920,0.832377,0.494668,0.979710,0.688233,0.841713,0.392653,0.396749,0.808778,0.523776
ENSMUSG00000038005_ProteinCoding_1,Hpf1,0.931968,0.907716,0.970122,0.868257,0.949421,0.602606,0.682575,0.892800,0.910755,0.638044,0.831588,0.505037,0.972134,0.643214,0.843135,0.406233,0.417408,0.778797,0.566269
ENSMUSG00000009894_ProteinCoding_2,Snap47,0.948731,0.923686,0.969853,0.866194,0.947946,0.547032,0.693481,0.898654,0.927204,0.645556,0.836695,0.497393,0.978968,0.677114,0.845601,0.391702,0.398121,0.802580,0.527027
ENSMUSG00000009894_ProteinCoding_1,Snap47,0.948693,0.923533,0.969771,0.865004,0.947587,0.548111,0.692725,0.898388,0.926990,0.645533,0.836715,0.496230,0.978885,0.675839,0.846054,0.392233,0.398404,0.802325,0.527208
ENSMUSG00000030122_ProteinCoding_1,Ptms,0.951518,0.935521,0.969573,0.862239,0.940277,0.598389,0.703318,0.876826,0.897361,0.652216,0.805009,0.482837,0.971065,0.675537,0.845202,0.334666,0.359932,0.805832,0.581530
ENSMUSG00000024038_ProteinCoding_1,Ndufv3,0.915651,0.877695,0.969533,0.897246,0.960467,0.505239,0.646161,0.932126,0.953489,0.577286,0.883537,0.574526,0.966858,0.630150,0.821954,0.499513,0.495937,0.748044,0.478535
ENSMUSG00000036751_ProteinCoding_1,Cox6b1,0.934276,0.901623,0.969524,0.870112,0.944960,0.549026,0.677078,0.909558,0.935669,0.624559,0.848737,0.521400,0.975291,0.655030,0.839657,0.443760,0.435324,0.778199,0.527630
ENSMUSG00000020949_ProteinCoding_2,Fkbp3,0.945322,0.916074,0.969485,0.856312,0.938614,0.561875,0.687072,0.890366,0.921640,0.650069,0.826604,0.491143,0.976620,0.669601,0.844030,0.407929,0.400078,0.801659,0.543235
ENSMUSG00000029621_ProteinCoding_1,Arpc1a,0.921429,0.892812,0.969433,0.894747,0.962414,0.501874,0.688781,0.921514,0.945651,0.580840,0.872596,0.571737,0.961575,0.660742,0.823808,0.462353,0.476431,0.750457,0.486245
ENSMUSG00000032959_NMD_1,Pebp1,0.903296,0.872579,0.969404,0.902559,0.971929,0.516886,0.610316,0.941860,0.940769,0.545419,0.892960,0.604779,0.958074,0.589342,0.825863,0.479696,0.506158,0.720018,0.481543
ENSMUSG00000032959_ProteinCoding_1,Pebp1,0.903217,0.872487,0.969362,0.902576,0.971926,0.516844,0.610182,0.941909,0.940760,0.545303,0.893020,0.604901,0.958016,0.589238,0.825827,0.479781,0.506311,0.719896,0.481432
ENSMUSG00000002844_ProteinCoding_1,Adprh,0.927349,0.905110,0.969266,0.877896,0.959736,0.588185,0.654732,0.914409,0.924027,0.598022,0.852462,0.530130,0.974398,0.623545,0.864661,0.427130,0.435909,0.751963,0.547923
ENSMUSG00000058317_ProteinCoding_3,Ube2e2,0.932862,0.910676,0.969255,0.873290,0.952943,0.580792,0.656366,0.894566,0.912617,0.618613,0.837545,0.510835,0.969883,0.631226,0.859992,0.380993,0.407338,0.777529,0.553550
ENSMUSG00000038965_NMD_1,Ube2l3,0.917272,0.886933,0.969095,0.890677,0.959313,0.504391,0.646670,0.920945,0.944197,0.584935,0.866809,0.569927,0.962376,0.624367,0.830450,0.467018,0.474357,0.747747,0.465988
ENSMUSG00000058076_ProteinCoding_1,Sdhc,0.966635,0.947158,0.968908,0.840578,0.921037,0.586595,0.744371,0.844532,0.901995,0.719588,0.772676,0.433294,0.978747,0.737364,0.850343,0.320580,0.318953,0.849746,0.563656
ENSMUSG00000029152_ProteinCoding_5,Ociad1,0.936476,0.909322,0.968870,0.871891,0.955292,0.558978,0.675635,0.910310,0.927947,0.620020,0.853140,0.515297,0.975773,0.648893,0.847911,0.422914,0.431579,0.779545,0.538210
ENSMUSG00000078923_ProteinCoding_1,Ube2v1,0.923312,0.900890,0.968850,0.880422,0.962863,0.568818,0.655569,0.916939,0.924439,0.595617,0.864517,0.533165,0.971905,0.624927,0.850101,0.434817,0.453762,0.756558,0.539370
ENSMUSG00000090841_ProteinCoding_5,Myl6,0.924329,0.896026,0.968504,0.879712,0.958182,0.573917,0.652725,0.924697,0.931231,0.588240,0.869639,0.541268,0.975762,0.619685,0.855054,0.451905,0.458271,0.746180,0.547831
ENSMUSG00000038965_ProteinCoding_2,Ube2l3,0.921639,0.889442,0.968398,0.889253,0.958431,0.490312,0.654365,0.919154,0.950540,0.589943,0.866307,0.565744,0.964588,0.637363,0.820952,0.468189,0.470450,0.756688,0.459854
ENSMUSG00000032294_ProteinCoding_1,Pkm,0.920813,0.890693,0.968158,0.880569,0.959638,0.535674,0.668343,0.921728,0.947904,0.595177,0.872110,0.543501,0.972514,0.637563,0.847842,0.489409,0.478887,0.751466,0.496866
ENSMUSG00000032294_ProteinCoding_2,Pkm,0.920681,0.890546,0.968116,0.880551,0.959722,0.535780,0.668209,0.921857,0.947993,0.595110,0.872247,0.543733,0.972526,0.637331,0.847997,0.489729,0.479148,0.751064,0.496755
ENSMUSG00000033379_ProteinCoding_1,Atp6v0b,0.939372,0.913739,0.968096,0.869741,0.948883,0.575208,0.669525,0.910736,0.926078,0.614335,0.846035,0.507157,0.978191,0.645584,0.861715,0.414109,0.418260,0.773814,0.551418
ENSMUSG00000024121_ProteinCoding_1,Atp6v0c,0.921332,0.892974,0.968076,0.885531,0.962205,0.535288,0.652974,0.929549,0.940490,0.570960,0.877393,0.564462,0.968227,0.626397,0.837390,0.464252,0.473452,0.741760,0.514439
ENSMUSG00000075706_ProteinCoding_1,Gpx4,0.946215,0.925469,0.967922,0.857360,0.937709,0.603455,0.706919,0.889475,0.910803,0.661184,0.817941,0.465612,0.980727,0.678685,0.862305,0.381531,0.377118,0.803789,0.577070
ENSMUSG00000031708_other_1,Tecr,0.950388,0.934942,0.967819,0.845088,0.928486,0.630548,0.707165,0.868265,0.890658,0.684298,0.793018,0.448251,0.977445,0.681778,0.868145,0.343854,0.349338,0.812663,0.600459
ENSMUSG00000026150_ProteinCoding_1,Mff,0.950227,0.930607,0.967701,0.847474,0.935314,0.636499,0.697588,0.872254,0.896602,0.666463,0.801634,0.448525,0.981555,0.660732,0.872604,0.352063,0.352294,0.808942,0.614262
ENSMUSG00000024381_ProteinCoding_2,Bin1,0.943656,0.932131,0.967461,0.863559,0.929527,0.586198,0.718871,0.858706,0.889881,0.663391,0.783587,0.476399,0.961769,0.714330,0.854992,0.311938,0.343849,0.812411,0.563695

In [22]:
corr_df.loc[corr_df['Gene'].str.contains("Celf4"),]

,Gene,All Neuronal,All Glutamatergic,All GABAergic,CGE Class,MGE Class,L4 IT,L6 CT,L6 IT Car3,Sncg,Pvalb,Sst,Sst Chodl,Astro,Oligo,Endo,VLMC,Peri,L4 L5 IT,Vip Sncg
ENSMUSG00000024268_NMD_1,Celf4,0.726540,0.683662,0.870069,0.890719,0.946049,0.375370,0.409005,0.975215,0.922262,0.267732,0.972456,0.751555,0.845597,0.362318,0.716352,0.694643,0.710424,0.471435,0.313190
ENSMUSG00000024268_ProteinCoding_1,Celf4,0.740486,0.696898,0.876430,0.901441,0.948431,0.328852,0.443044,0.978830,0.939223,0.272856,0.975586,0.764752,0.848897,0.407109,0.704574,0.698455,0.718142,0.487687,0.279900
ENSMUSG00000024268_ProteinCoding_2,Celf4,0.726865,0.682150,0.866423,0.895603,0.942930,0.313726,0.427258,0.978813,0.934438,0.250971,0.978610,0.772423,0.837927,0.390687,0.693671,0.711055,0.730879,0.469239,0.263861

In [6]:
corr_df.iloc[:, 1:].corr()

,All Neuronal,All Glutamatergic,All GABAergic,CGE Class,MGE Class,L4 IT,L6 CT,L6 IT Car3,Sncg,Pvalb,Sst,Sst Chodl,Astro,Oligo,Endo,VLMC,Peri,L4 L5 IT,Vip Sncg
All Neuronal,1.000000,0.996846,0.963520,0.839037,0.897899,0.841191,0.928886,0.804662,0.874436,0.852829,0.721683,0.363468,0.982800,0.910445,0.973343,0.256637,0.240569,0.951905,0.822454
All Glutamatergic,0.996846,1.000000,0.942566,0.799541,0.865492,0.870766,0.946887,0.761375,0.836176,0.884738,0.670851,0.295766,0.968070,0.926911,0.967409,0.185137,0.169266,0.968537,0.857402
All GABAergic,0.963520,0.942566,1.000000,0.951960,0.980988,0.732755,0.809675,0.929718,0.965903,0.689972,0.874639,0.593641,0.993402,0.788751,0.965186,0.491354,0.483264,0.841630,0.688208
CGE Class,0.839037,0.799541,0.951960,1.000000,0.986956,0.529577,0.612080,0.987705,0.985728,0.447450,0.968874,0.801542,0.917176,0.597347,0.864837,0.709696,0.714621,0.648272,0.465559
MGE Class,0.897899,0.865492,0.980988,0.986956,1.000000,0.622620,0.696394,0.980815,0.991324,0.543401,0.949399,0.727609,0.960215,0.671022,0.916550,0.638679,0.634631,0.726461,0.563858
L4 IT,0.841191,0.870766,0.732755,0.529577,0.622620,1.000000,0.840027,0.489721,0.548810,0.883672,0.377713,-0.030756,0.787068,0.789207,0.854508,-0.130088,-0.147128,0.878315,0.987395
L6 CT,0.928886,0.946887,0.809675,0.612080,0.696394,0.840027,1.000000,0.561285,0.674745,0.952806,0.458159,0.053262,0.855033,0.988065,0.853994,-0.038235,-0.068475,0.977464,0.857198
L6 IT Car3,0.804662,0.761375,0.929718,0.987705,0.980815,0.489721,0.561285,1.000000,0.983801,0.383870,0.990011,0.830575,0.896030,0.535740,0.842389,0.765093,0.760933,0.592483,0.420528
Sncg,0.874436,0.836176,0.965903,0.985728,0.991324,0.548810,0.674745,0.983801,1.000000,0.505078,0.961162,0.758671,0.941471,0.657833,0.886276,0.688471,0.676354,0.695447,0.492880
Pvalb,0.852829,0.884738,0.689972,0.447450,0.543401,0.883672,0.952806,0.383870,0.505078,1.000000,0.263484,-0.157956,0.750408,0.947578,0.785019,-0.257566,-0.283234,0.965939,0.906626
Sst,0.721683,0.670851,0.874639,0.968874,0.949399,0.377713,0.458159,0.990011,0.961162,0.263484,1.000000,0.892777,0.831363,0.433846,0.766351,0.841318,0.838910,0.484554,0.303286
Sst Chodl,0.363468,0.295766,0.593641,0.801542,0.727609,-0.030756,0.053262,0.830575,0.758671,-0.157956,0.892777,1.000000,0.512688,0.046437,0.420926,0.957511,0.979712,0.081136,-0.116361
Astro,0.982800,0.968070,0.993402,0.917176,0.960215,0.787068,0.855033,0.896030,0.941471,0.750408,0.831363,0.512688,1.000000,0.830621,0.981420,0.418746,0.403169,0.882663,0.749629
Oligo,0.910445,0.926911,0.788751,0.597347,0.671022,0.789207,0.988065,0.535740,0.657833,0.947578,0.433846,0.046437,0.830621,1.000000,0.822905,-0.053899,-0.079053,0.971992,0.813103
Endo,0.973343,0.967409,0.965186,0.864837,0.916550,0.854508,0.853994,0.842389,0.886276,0.785019,0.766351,0.420926,0.981420,0.822905,1.000000,0.327831,0.310597,0.894582,0.815783
VLMC,0.256637,0.185137,0.491354,0.709696,0.638679,-0.130088,-0.038235,0.765093,0.688471,-0.257566,0.841318,0.957511,0.418746,-0.053899,0.327831,1.000000,0.988829,-0.031223,-0.218329
Peri,0.240569,0.169266,0.483264,0.714621,0.634631,-0.147128,-0.068475,0.760933,0.676354,-0.283234,0.838910,0.979712,0.403169,-0.079053,0.310597,0.988829,1.000000,-0.049858,-0.235516
L4 L5 IT,0.951905,0.968537,0.841630,0.648272,0.726461,0.878315,0.977464,0.592483,0.695447,0.965939,0.484554,0.081136,0.882663,0.971992,0.894582,-0.031223,-0.049858,1.000000,0.887907
Vip Sncg,0.822454,0.857402,0.688208,0.465559,0.563858,0.987395,0.857198,0.420528,0.492880,0.906626,0.303286,-0.116361,0.749629,0.813103,0.815783,-0.218329,-0.235516,0.887907,1.000000